services:
  tink:
    image: ghcr.io/mrasong/tink:latest
    container_name: tink
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - TINK_DATA_DIR=/data
      - TINK_PORT=5021
      # If not set, a random Admin Secret Key will be generated on first startup and logged once
      - TINK_INITIAL_TOKEN=sk-tink-change_me_to_a_secure_token
      - TINK_DASHBOARD_ROUTE=/dashboard
    ports:
      - "5021:5021"
    volumes:
      - ./data:/data
